# Generated by Django 3.0.8 on 2020-07-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_debit',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='supplier_credit',
            name='status',
        ),
        migrations.RemoveField(
            model_name='supplier_slip',
            name='status',
        ),
        migrations.AddField(
            model_name='customer_debit',
            name='Paid_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='debit_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier_credit',
            name='Paid_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier_slip',
            name='debit_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
