# Generated by Django 3.0 on 2020-10-26 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20201026_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_dena',
            old_name='Amount',
            new_name='amount',
        ),
    ]
